std = "roblox"

[rules]
global_usage = "allow"
multiple_statements = "allow"
shadowing = "allow"
unscoped_variables = "allow"
unused_variable = "allow"
parenthese_conditions = "allow"
incorrect_standard_library_use = "allow"
if_same_then_else = "allow"
deprecated = "allow"
undefined_variable = "allow"
divide_by_zero = "allow"
unbalanced_assignments = "allow"