name: Development Linting

on:
        schedule:
                - cron: '0 0 * * 0'
        workflow_dispatch:

permissions:
        contents: write

jobs:
        lint:
                name: lint
                runs-on: ubuntu-latest

                steps:
                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: luajit
                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 5.1
                        - name: Apply fix to luajit
                          working-directory: .lua/bin
                          run: mv luajit* luajit
                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}

                        - name: Generate release data
                          run: |
                                  echo "tag=linting-$(date +%s)" >> $GITHUB_OUTPUT
                          id: release-data

                        - uses: NTBBloodbath/selene-action@v1.0.0
                          name: Lint Scripts contained in /source
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}
                                  args: --allow-warnings ./source

                        - uses: actions/checkout@v4.1.1
                        - uses: stefanzweifel/git-auto-commit-action@v5
                          with:
                                  commit_message: ${{ steps.release-data.outputs.tag }}
                                  tagging_message: ${{ steps.release-data.outputs.tag }}
                                  add_options: '-A'
                                  file_pattern: './source/**.lua'

