name: Development Publish

on:
        push:
                branches: [development]
                paths:
                        - source/**
                        - Obfuscator/**
                        - yolus-source/**
                        - .github/**
        workflow_dispatch:

jobs:
        build:
                name: build
                runs-on: ubuntu-latest
                permissions:
                        contents: write
                steps:
                        - uses: actions/checkout@v4.1.1
                        - uses: actions/setup-dotnet@v4
                          with:
                                  dotnet-version: 7.0
                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: luajit

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 5.1

                        - id: files
                          uses: jitterbit/get-changed-files@v1

                        - name: Format changed files
                          id: formatting
                          run: |
                                  added=$(echo "${{ steps.files.outputs.added }}" | tr ' ' '\n' | sed 's/^/+ /g')
                                  modified=$(echo "${{ steps.files.outputs.modified }}" | tr ' ' '\n' | sed 's/^/+ /g')
                                  removed=$(echo "${{ steps.files.outputs.removed }}" | tr ' ' '\n' | sed 's/^/- /g')
                                                        
                                  if [[ $(echo "$added" | grep -cE '^(\+ ){0,1}$') -eq 1 ]]; then
                                    added="# None"
                                  fi

                                  if [[ $(echo "$modified" | grep -cE '^(\+ ){0,1}$') -eq 1 ]]; then
                                    modified="# None"
                                  fi

                                  if [[ $(echo "$removed" | grep -cE '^(\- ){0,1}$') -eq 1 ]]; then
                                    removed="# None"
                                  fi
                                                        
                                  echo "added=$added" >> $GITHUB_OUTPUT
                                  echo "modified=$modified" >> $GITHUB_OUTPUT
                                  echo "removed=$removed" >> $GITHUB_OUTPUT

                        - name: Generate release data
                          run: |
                                  echo "tag=dev-$(date +%s)" >> $GITHUB_OUTPUT
                                  echo "title=VSDS ${{ github.ref_name }} release [$(date --utc +%FT%TZ)]" >> $GITHUB_OUTPUT
                                  echo "date=$(date +%F_%T)" >> $GITHUB_OUTPUT
                          id: release-data

                        - name: Apply fix to luajit
                          working-directory: .lua/bin
                          run: mv luajit* luajit

                        - name: Set up production version for rojo
                          run: mv release.project.json default.project.json

                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}

                        - name: Obfuscate Source Files
                          working-directory: Obfuscator
                          run: dotnet YolusCLI.dll

                        - name: Build
                          run: rojo build -o ./vsds-${{ github.ref_name }}.rbxm

                        - name: Publish Loader
                          uses: fjogeleit/http-request-action@v1.15.4
                          with:
                                  url: 'http://upload.furwithpawbs.social/?assetId=${{ secrets.VSDS_ASSETID }}'
                                  method: 'POST'
                                  contentType: 'multipart/form-data'
                                  files: '{ "file": "vsds-${{ github.ref_name }}.rbxm" }'
                                  customHeaders: '{ "authentication": "${{ secrets.VSDS_COMMITKEY }}" }'
                                  timeout: 10000

                        - uses: actions/upload-artifact@v4.3.1
                          with:
                                  name: VSDS V3 DEVELOPMENT BUILD
                                  path: vsds-${{ github.ref_name }}.rbxm

                        - name: Create Release
                          uses: softprops/action-gh-release@v2
                          with:
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-${{ github.ref_name }}.rbxm
                                  body: |
                                          ### Newest VSDS update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`
                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-${{ github.ref_name }}.rbxm`

                                          **Files Modified:**
                                          Added:
                                            ```diff
                                            ${{ steps.formatting.outputs.added }}
                                            ```
                                          Modified:
                                            ```diff
                                            ${{ steps.formatting.outputs.modified }}
                                            ```
                                          Removed:
                                            ```diff
                                            ${{ steps.formatting.outputs.removed }}
                                            ```
                                  draft: false
                                  make_latest: true

                        - name: Create Release [PUBLIC]
                          uses: softprops/action-gh-release@v2
                          with:
                                  repository: Bracketed/VSDS
                                  token: ${{ secrets.VSDS_PUBCOMMIT }}
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-${{ github.ref_name }}.rbxm
                                  body: |
                                          ### Newest VSDS update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`
                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-${{ github.ref_name }}.rbxm`

                                          **Files Modified:**
                                          Added:
                                            ```diff
                                            ${{ steps.formatting.outputs.added }}
                                            ```
                                          Modified:
                                            ```diff
                                            ${{ steps.formatting.outputs.modified }}
                                            ```
                                          Removed:
                                            ```diff
                                            ${{ steps.formatting.outputs.removed }}
                                            ```
                                  draft: false
                                  make_latest: true

                        - name: Discord Webhook Action
                          uses: tsickert/discord-webhook@v5.3.0
                          with:
                                  username: '@Github Actions'
                                  avatar-url: https://avatars.githubusercontent.com/in/15368
                                  webhook-url: ${{ secrets.VSDS_WEBHOOK }}
                                  embed-title: ${{ steps.release-data.outputs.title }}
                                  embed-color: 000000
                                  embed-url: https://create.roblox.com/store/asset/16582923129
                                  embed-author-name: ${{ steps.release-data.outputs.tag }}
                                  filename: vsds-${{ github.ref_name }}.rbxm
                                  embed-description: |
                                          ### Newest VSDS update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`
                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-${{ github.ref_name }}.rbxm`

                                          **Files Modified:**
                                          Added:
                                            ```diff
                                            ${{ steps.formatting.outputs.added }}
                                            ```
                                          Modified:
                                            ```diff
                                            ${{ steps.formatting.outputs.modified }}
                                            ```
                                          Removed:
                                            ```diff
                                            ${{ steps.formatting.outputs.removed }}
                                            ```
