name: Development Publish

on:
        push:
                branches: [development]
        workflow_dispatch:

env:
        assetId: 0
        url: https://apis.roblox.com/assets/v1/assets

jobs:
        build:
                name: build
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v4.1.1
                        - uses: actions/setup-dotnet@v4
                          with:
                                  dotnet-version: 7.0

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: luajit

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 5.1

                        - name: Apply fix to luajit
                          working-directory: .lua/bin
                          run: mv luajit* luajit

                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}

                        - name: Obfuscate Source Files
                          working-directory: Obfuscator
                          run: dotnet YolusCLI.dll

                        - name: Build
                          run: rojo build -o vsds.rbxm release.project.json

                        - uses: actions/upload-artifact@v4.3.1
                          with:
                                  name: VSDS V3 DEVELOPMENT BUILD
                                  path: vsds.rbxm

                        - name: Release changelog to Discord
                          uses: kludge-cs/gitcord-release-changelogger@v3.0.0
                          with:
                                  release-body: ${{ github.event.release.body }}
                                  release-name: ${{ github.ref_name }}
                                  webhook-url: ${{ secrets.VSDS_WEBHOOKKEY }}

                        #- name: Publish VSDS V3 Development Version
                        #  uses: fjogeleit/http-request-action@v1.15.4
                        #  with:
                        #          url: '${{ secrets.PUBURL2 }}/?assetId=${{ secrets.NIGHTLY_MODULE_ID }}'
                        #          method: 'POST'
                        #          contentType: 'multipart/form-data'
                        #          files: '{ "file": "module.rbxm" }'
                        #          customHeaders: '{ "upload-secret": "${{ secrets.PUBURL2_SECRET }}" }'
                        #          timeout: 10000
                        #          preventFailureOnNoResponse: 'true'
