name: Publish VSDS Loader

on:
        push:
                branches: [development]
                paths:
                        - src/loader/**
                        - loader.project.json
                        - vsds.loader.project.json
                        - selene*
                        - aftman*
                        #- '.github/**' # for developmental perposes
        workflow_dispatch:

env:
        publish: 'true'

jobs:
        publish:
                name: Build & Publish Loader
                runs-on: ubuntu-latest
                permissions:
                        contents: write
                steps:
                        - uses: actions/checkout@v4.1.1
                        - uses: actions/setup-dotnet@v4
                          with:
                                  dotnet-version: 7.0
                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: luajit

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 5.1

                        - name: Generate release data
                          run: |
                                  echo "tag=loader-${{ github.ref_name }}-$(date +%s)" >> $GITHUB_OUTPUT
                                  echo "title=VSDS Loader ${{ github.ref_name }} release [$(date --utc +%FT%TZ)]" >> $GITHUB_OUTPUT
                                  echo "date=$(date +%F_%T)" >> $GITHUB_OUTPUT
                          id: release-data

                        - name: Apply fix to luajit
                          working-directory: .lua/bin
                          run: mv luajit* luajit

                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}

                        - name: Cache Roblox LuaU Library
                          id: rblx-libcache
                          uses: actions/cache@v4.0.2
                          with:
                                  path: roblox.yml
                                  key: roblox-std

                        - name: Check standard Roblox LuaU Lib status
                          id: rblx-libs
                          env:
                                  DID_CACHE: ${{steps.rblx-libcache.outputs.cache-hit}}
                          run: |
                                  if test -f roblox.yml; then
                                   CUR_ROBLOX_STD_TIMEDATE="$(date +%s -d "$(cat roblox.yml |  head -n 1 | grep -oP "\d{4}-\d{2}-\d{2}(?=\s+\d{2}:\d{2}:\d{2})")")"
                                  else
                                   CUR_ROBLOX_STD_TIMEDATE=0
                                  fi
                                  if [ "$DID_CACHE" == "true" ] 
                                  then
                                    if [ "$(($(date +%s)-$CUR_ROBLOX_STD_TIMEDATE))" -ge "604800" ]
                                    then
                                      echo "::notice ::Roblox Standard Library Cache is out of date by 1 week, requiring a refresh of the standard library cache."
                                      echo "fetch=true" >> $GITHUB_OUTPUT
                                    else
                                     echo "fetch=false" >> $GITHUB_OUTPUT
                                    fi
                                  else
                                    echo "fetch=true" >> $GITHUB_OUTPUT
                                  fi

                        - name: Download Lua Minify libraries from source
                          uses: GuillaumeFalourd/clone-github-repo-action@v2.3
                          with:
                                  owner: 'Bracketed'
                                  repository: 'VSDS-LUA'
                                  access-token: ${{ secrets.VSDS_PUBCOMMIT }}

                        - name: Apply fix to VSDS lua binaries and minification libraries
                          run: mv VSDS-LUA Lua

                        - name: Download Yolus Obfuscator libraries from source
                          uses: GuillaumeFalourd/clone-github-repo-action@v2.3
                          with:
                                  owner: 'Bracketed'
                                  repository: 'VSDS-OBFUSCATOR'
                                  access-token: ${{ secrets.VSDS_PUBCOMMIT }}

                        - name: Apply fix to VSDS yolus binaries and obfuscation libraries
                          run: mv VSDS-OBFUSCATOR Yolus

                        - name: Extract Font libraries
                          run: mv Yolus/Fonts Fonts

                        - name: Build Obfuscator
                          working-directory: Yolus
                          run: dotnet build --output ../Obfuscator

                        - name: Set versioning for VSDS release.
                          working-directory: ./src/loader
                          run: sed -i -e "s/UNKNOWN/${{ steps.release-data.outputs.tag }}/g" VSDS-VER.model.json

                        - name: Obfuscate Source Files
                          working-directory: Obfuscator
                          run: dotnet YolusCLI.dll

                        - name: Retrieve Latest Roblox Verification Libraries
                          if: steps.rblx-libs.outputs.fetch == 'true'
                          run: selene generate-roblox-std

                        - name: Verify Scripts contained in /src/loader
                          run: selene ./src/loader

                        - name: Cat entry file to check for formatting
                          run: cat init.lua
                          working-directory: src/loader

                        - name: Build
                          run: rojo build -o ./vsds-loader-${{ github.ref_name }}.rbxmx vsds.loader.project.json

                        - name: Check for API uptime
                          if: env.publish == 'true'
                          uses: fjogeleit/http-request-action@v1.15.4
                          with:
                                  url: 'https://roblox-apis.bracketed.co.uk/vsds'
                                  method: 'GET'
                                  timeout: 10000

                        - name: Set API env variable
                          if: success() && env.publish == 'true'
                          run: echo "api=true" >> $GITHUB_ENV

                        - name: Publish Loader
                          if: env.api == 'true'
                          uses: fjogeleit/http-request-action@v1.15.4
                          with:
                                  url: 'https://roblox-apis.bracketed.co.uk/vsds/upload'
                                  method: 'POST'
                                  contentType: 'multipart/form-data'
                                  files: '{ "file": "vsds-loader-${{ github.ref_name }}.rbxmx" }'
                                  customHeaders: '{ "vsds-authorisation": "${{ secrets.VSDS_COMMITKEY }}" }'
                                  timeout: 10000

                        - uses: actions/upload-artifact@v4.3.1
                          with:
                                  name: VSDS LOADER - ${{ steps.release-data.outputs.tag }}
                                  path: vsds-loader-${{ github.ref_name }}.rbxmx

                        - name: Create Release
                          if: env.api == 'true'
                          uses: softprops/action-gh-release@v2
                          with:
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-loader-${{ github.ref_name }}.rbxmx
                                  body: |
                                          ### Newest VSDS Loader update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-loader-${{ github.ref_name }}.rbxmx`

                                  draft: false
                                  make_latest: true

                        - name: Create Release [PUBLIC]
                          if: env.api == 'true'
                          uses: softprops/action-gh-release@v2
                          with:
                                  repository: Bracketed/VSDS
                                  token: ${{ secrets.VSDS_PUBCOMMIT }}
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-loader-${{ github.ref_name }}.rbxmx
                                  body: |
                                          ### Newest VSDS Loader update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-loader-${{ github.ref_name }}.rbxmx`

                                  draft: false
                                  make_latest: true

                        - name: Discord Webhook Action
                          if: env.api == 'true'
                          uses: tsickert/discord-webhook@v5.3.0
                          with:
                                  username: '@Github Actions'
                                  avatar-url: https://avatars.githubusercontent.com/in/15368
                                  webhook-url: ${{ secrets.VSDS_WEBHOOK }}
                                  embed-title: ${{ steps.release-data.outputs.title }}
                                  embed-color: 000000
                                  embed-url: https://create.roblox.com/store/asset/16582923129
                                  embed-author-name: ${{ steps.release-data.outputs.tag }}
                                  filename: vsds-loader-${{ github.ref_name }}.rbxmx
                                  embed-description: |
                                          ### Newest VSDS Loader update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-loader-${{ github.ref_name }}.rbxmx`
