name: Publish VSDS Plugin

on:
        push:
                branches: [development]
                paths:
                        - src/plugin/**
                        - plugin.project.json
                        - vsds.plugin.project.json
                        - selene*
                        - aftman*
                        #- '.github/**' # for developmental perposes
        workflow_dispatch:

env:
        publish: false

jobs:
        publish:
                name: Build & Publish Plugin
                runs-on: ubuntu-latest
                permissions:
                        contents: write
                steps:
                        - uses: actions/checkout@v4.1.1
                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: luajit

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 5.1

                        - name: Generate release data
                          run: |
                                  echo "tag=plugin-${{ github.ref_name }}-$(date +%s)" >> $GITHUB_OUTPUT
                                  echo "title=VSDS Plugin ${{ github.ref_name }} release [$(date --utc +%FT%TZ)]" >> $GITHUB_OUTPUT
                                  echo "date=$(date +%F_%T)" >> $GITHUB_OUTPUT
                          id: release-data

                        - name: Apply fix to luajit
                          working-directory: .lua/bin
                          run: mv luajit* luajit

                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}

                        - name: Set versioning for VSDS release.
                          working-directory: src/plugin/source
                          run: sed -i -e "s/VERSION_UNKNOWN/${{ steps.release-data.outputs.tag }}/g" Configuration.lua

                        - name: Build
                          run: rojo build -o ./vsds-plugin-${{ github.ref_name }}.rbxmx vsds.plugin.project.json

                        - name: Publish Plugin
                          if: env.publish == true
                          uses: fjogeleit/http-request-action@v1.15.4
                          with:
                                  url: 'http://nlc4euhknh.furwithpawbs.social/?assetId=${{ secrets.VSDS_PLUGIN_ASSETID }}'
                                  method: 'POST'
                                  contentType: 'multipart/form-data'
                                  files: '{ "file": "vsds-plugin-${{ github.ref_name }}.rbxmx" }'
                                  customHeaders: '{ "authentication": "${{ secrets.VSDS_COMMITKEY }}" }'
                                  timeout: 10000

                        - uses: actions/upload-artifact@v4.3.1
                          with:
                                  name: VSDS PLUGIN - ${{ steps.release-data.outputs.tag }}
                                  path: vsds-plugin-${{ github.ref_name }}.rbxmx

                        - name: Create Release
                          if: env.publish == true
                          uses: softprops/action-gh-release@v2
                          with:
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-plugin-${{ github.ref_name }}.rbxmx
                                  body: |
                                          ### Newest VSDS Plugin update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-plugin-${{ github.ref_name }}.rbxmx`

                                  draft: false
                                  make_latest: true

                        - name: Create Release [PUBLIC]
                          if: env.publish == true
                          uses: softprops/action-gh-release@v2
                          with:
                                  repository: Bracketed/VSDS
                                  token: ${{ secrets.VSDS_PUBCOMMIT }}
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-plugin-${{ github.ref_name }}.rbxmx
                                  body: |
                                          ### Newest VSDS Plugin update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-plugin-${{ github.ref_name }}.rbxmx`

                                  draft: false
                                  make_latest: true

                        - name: Discord Webhook Action
                          if: env.publish == true
                          uses: tsickert/discord-webhook@v5.3.0
                          with:
                                  username: '@Github Actions'
                                  avatar-url: https://avatars.githubusercontent.com/in/15368
                                  webhook-url: ${{ secrets.VSDS_WEBHOOK }}
                                  embed-title: ${{ steps.release-data.outputs.title }}
                                  embed-color: 000000
                                  embed-url: https://create.roblox.com/store/asset/16582923129
                                  embed-author-name: ${{ steps.release-data.outputs.tag }}
                                  filename: vsds-plugin-${{ github.ref_name }}.rbxmx
                                  embed-description: |
                                          ### Newest VSDS Plugin update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-plugin-${{ github.ref_name }}.rbxmx`
