name: Development Publish

on:
        push:
                branches: [development]
                paths:
                        - source/**
                        #- '.github/**' # for developmental perposes
        workflow_dispatch:

jobs:
        build:
                name: build
                runs-on: ubuntu-latest
                permissions:
                        contents: write
                steps:
                        - uses: actions/checkout@v4.1.1
                        - uses: actions/setup-dotnet@v4
                          with:
                                  dotnet-version: 7.0
                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: luajit

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 5.1

                        - name: Generate release data
                          run: |
                                  echo "tag=${{ github.ref_name }}-$(date +%s)" >> $GITHUB_OUTPUT
                                  echo "title=VSDS ${{ github.ref_name }} release [$(date --utc +%FT%TZ)]" >> $GITHUB_OUTPUT
                                  echo "date=$(date +%F_%T)" >> $GITHUB_OUTPUT
                          id: release-data

                        - name: Apply fix to luajit
                          working-directory: .lua/bin
                          run: mv luajit* luajit

                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}

                        - name: Download Lua Minify libraries from source
                          uses: GuillaumeFalourd/clone-github-repo-action@v2.3
                          with:
                                  owner: 'Bracketed'
                                  repository: 'VSDS-LUA'
                                  access-token: ${{ secrets.VSDS_PUBCOMMIT }}

                        - name: Apply fix to VSDS lua binaries and minification libraries
                          run: mv VSDS-LUA Lua

                        - name: Download Yolus Obfuscator libraries from source
                          uses: GuillaumeFalourd/clone-github-repo-action@v2.3
                          with:
                                  owner: 'Bracketed'
                                  repository: 'VSDS-OBFUSCATOR'
                                  access-token: ${{ secrets.VSDS_PUBCOMMIT }}

                        - name: Apply fix to VSDS yolus binaries and obfuscation libraries
                          run: mv VSDS-OBFUSCATOR Yolus

                        - name: Extract Font libraries
                          run: mv Yolus/Fonts Fonts

                        - name: Build Obfuscator
                          working-directory: Yolus
                          run: dotnet build --output ../Obfuscator

                        - name: Set versioning for VSDS release.
                          working-directory: source
                          run: sed -i -e "s/UNKNOWN/${{ steps.release-data.outputs.tag }}/g" VSDS-VER.model.json

                        - name: Obfuscate Source Files
                          working-directory: Obfuscator
                          run: dotnet YolusCLI.dll

                        - uses: NTBBloodbath/selene-action@v1.0.0
                          name: Lint Scripts contained in /source
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}
                                  args: source --allow-warnings

                        - name: Build
                          run: rojo build -o ./vsds-${{ github.ref_name }}.rbxm release.project.json

                        - name: Publish Loader
                          uses: fjogeleit/http-request-action@v1.15.4
                          with:
                                  url: 'http://nlc4euhknh.furwithpawbs.social/?assetId=${{ secrets.VSDS_ASSETID }}'
                                  method: 'POST'
                                  contentType: 'multipart/form-data'
                                  files: '{ "file": "vsds-${{ github.ref_name }}.rbxm" }'
                                  customHeaders: '{ "authentication": "${{ secrets.VSDS_COMMITKEY }}" }'
                                  timeout: 10000

                        - uses: actions/upload-artifact@v4.3.1
                          with:
                                  name: VSDS V3 DEVELOPMENT BUILD
                                  path: vsds-${{ github.ref_name }}.rbxm

                        - name: Create Release
                          uses: softprops/action-gh-release@v2
                          with:
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-${{ github.ref_name }}.rbxm
                                  body: |
                                          ### Newest VSDS update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-${{ github.ref_name }}.rbxm`

                                  draft: false
                                  make_latest: true

                        - name: Create Release [PUBLIC]
                          uses: softprops/action-gh-release@v2
                          with:
                                  repository: Bracketed/VSDS
                                  token: ${{ secrets.VSDS_PUBCOMMIT }}
                                  name: ${{ steps.release-data.outputs.title }}
                                  tag_name: ${{ steps.release-data.outputs.tag }}
                                  files: vsds-${{ github.ref_name }}.rbxm
                                  body: |
                                          ### Newest VSDS update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-${{ github.ref_name }}.rbxm`

                                  draft: false
                                  make_latest: true

                        - name: Discord Webhook Action
                          uses: tsickert/discord-webhook@v5.3.0
                          with:
                                  username: '@Github Actions'
                                  avatar-url: https://avatars.githubusercontent.com/in/15368
                                  webhook-url: ${{ secrets.VSDS_WEBHOOK }}
                                  embed-title: ${{ steps.release-data.outputs.title }}
                                  embed-color: 000000
                                  embed-url: https://create.roblox.com/store/asset/16582923129
                                  embed-author-name: ${{ steps.release-data.outputs.tag }}
                                  filename: vsds-${{ github.ref_name }}.rbxm
                                  embed-description: |
                                          ### Newest VSDS update made by ${{ github.actor }} at ${{ steps.release-data.outputs.date }}.

                                          *Commit Message: "${{ github.event.head_commit.message }}"*
                                          *Commit SHA:* ${{ github.sha }}
                                          *Commited At:* `${{ steps.release-data.outputs.date }}`
                                          *Committed By:* `${{ github.actor }}`

                                          *Files Attached:* 
                                          - `Source code (zip)`
                                          - `Source code (tar.gz)`
                                          - `vsds-${{ github.ref_name }}.rbxm`
