name: Development Publish

on:
        push:
                branches: [development]
        workflow_dispatch:

env:
        assetId: 0
        url: https://apis.roblox.com/assets/v1/assets

jobs:
        build:
                name: build
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v4.1.1
                        - uses: actions/setup-dotnet@v4
                          with:
                                  dotnet-version: '7.0'

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: '5.1'

                        - uses: leafo/gh-actions-lua@v10
                          with:
                                  luaVersion: 'luajit'

                        - uses: ok-nick/setup-aftman@v0.4.2
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}
                        - run: lua5.1 -v
                        - name: Build
                          run: rojo build -o vsds.rbxm release.project.json

                        - uses: actions/upload-artifact@v4.3.1
                          with:
                                  name: VSDS V3 DEVELOPMENT BUILD
                                  path: vsds.rbxm

                        - name: Test Obfuscation
                          working-directory: ./Build/RuntimeTool
                          run: dotnet YolusCLI.dll idk.lua

                        - name: Echo test file
                          working-directory: ./Build/RuntimeTool
                          run: cat idk-obfuscated.lua
                        #- name: Ping for new development release - Do this eventually
                        #  uses: tsickert/discord-webhook@v6.0.0

                        #- name: Publish VSDS V3 Development Version
                        #  uses: fjogeleit/http-request-action@v1.15.4
                        #  with:
                        #          url: '${{ secrets.PUBURL2 }}/?assetId=${{ secrets.NIGHTLY_MODULE_ID }}'
                        #          method: 'POST'
                        #          contentType: 'multipart/form-data'
                        #          files: '{ "file": "module.rbxm" }'
                        #          customHeaders: '{ "upload-secret": "${{ secrets.PUBURL2_SECRET }}" }'
                        #          timeout: 10000
                        #          preventFailureOnNoResponse: 'true'
